POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGl0byIsImlkIjoiNjk3Yjk5YTk1NWFiNjA3MTkzY2YyZmRhIiwiaWF0IjoxNzY5Nzc0Mzk2LCJleHAiOjE3Njk3Nzc5OTZ9.ZhKen405CYNP5YQ5SqPWBEw1zN-2PHcnW5g3Lk6IMdM

{
    "title": "Don Quijote de la Mancha",
    "author": "Cervantes",
    "url": "http://example.com/one-more-blog-entry",
    "likes": 3000
}

### Create blog entry without likes
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGl0byIsImlkIjoiNjk3Yjk5YTk1NWFiNjA3MTkzY2YyZmRhIiwiaWF0IjoxNzY5Nzk5MjA2LCJleHAiOjE3Njk4MDI4MDZ9.OiPquJJbrT64QARspuWc8HquGSOAueviNbDnXCFryIE

{
    "title": "A blog without likes",
    "author": "John Smith",
    "url": "http://example.com/one-more-blog-entry",
    "likes": 0  
}

### Create blog without title
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "John Smith",
    "url": "http://example.com/one-more-blog-entry",
    "likes": 0  
}

### Create blog without url
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "One more Blog Entry",
    "author": "John Smith",
    "likes": 0  
}

### List of all blog entries
GET http://localhost:3003/api/blogs