POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mozart",
  "number": "1111111111"
}

### Failing request: name too short
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mo",
  "number": "1111111111"
}
